### ISSUE TITLE
Problem running examples

### ISSUE THREAD

**Issue by c5sire** [trestletech/shinyTable#1]
Dear Jeff,

Your package 'shinyTable' seems to be what I was looking for!

However, I am having trouble to run the examples (still a 'shiny' novice, though). I have tried: runGitHub("shinyTable", "trestletech", subdir="inst/examples/01-simple") 

But get the following message:

Error in handler(binary, message) : 
  No handler registered for for type tbl:htable

I am running R 3.0.2 with latest shiny  0.8.0.99 on Windows XP.

Best regards,

Reinhard

**Comment by arunatma** [comment]
It seems the problem still exists.

I installed (in Win7) the shinyTable from github using install_github.  Changed my current working directory to the examples/01-simple

runApp() gets the new web page, showing the 5x5 grid. But, within 3 seconds, gets grayed out. Because of the error, as stated here.

**No handler registered for for type tbl:htable**

Is there a known solution for this?  Has it been reproducible?
